import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:humanbody/ItemOrgans.dart';
import 'package:humanbody/ItemSystem.dart';
import 'package:humanbody/Screens/Skeletal%20system/skeleton.dart';

import '../../videos.dart';
import '../Home.dart';
import '../Quiz_screens/Quiz_Skelton.dart';
import 'Joints.dart';

class Skeletol_System extends StatefulWidget {
  const Skeletol_System({Key? key}) : super(key: key);

  @override
  State<Skeletol_System> createState() => _Skeletol_SystemState();
}

class _Skeletol_SystemState extends State<Skeletol_System> {
  double screenWidth = 0;
  double screenHeight = 0;

  @override
  Widget build(BuildContext context) {
    screenHeight = MediaQuery.of(context).size.height;
    screenWidth = MediaQuery.of(context).size.width;

    return Scaffold(
      //backgroundColor: Colors.amberAccent,
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: const Color(0xffA8FFBF),
        elevation: 0,
        title: const Text(
          "Skeletol system",
          style: TextStyle(
            fontWeight: FontWeight.w900,
            color: Colors.black87,
            fontSize: 30,
          ),
        ),
        leading: IconButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) {
                  return const Home();
                },
              ),
            );
          },
          icon: const Icon(Icons.arrow_back),
        ),
      ),

      body: ListView(
        scrollDirection: Axis.vertical,
        shrinkWrap: true,
        children: [
          SizedBox(
            height: 260.h,
            child: Container(
              height: 190.h,
              width: 100.h,
              decoration: const BoxDecoration(
                color: Color(0xffA8FFBF),
                borderRadius: BorderRadius.only(
                    bottomRight: Radius.circular(90),
                    bottomLeft: Radius.circular(90)),
              ),
              child: Image.asset(
                  "assets/images/skeletalSystem/skeletalSystem-removebg-preview.png"),
            ),
          ),
          SizedBox(
            height: 15.h,
          ),
          const ItemSystem(
              asset:
                  "assets/images/skeletalSystem/skelton/Chimpanzee-skeleton-3d-model-2.jpeg",
              title: "Skelton",
              desc:
                  "The function of the skeleton is to provide support, shape, and protection for the body's internal organs, as well as to facilitate movement through the attachment of muscles.",
              menu: Skeleton()),
          ItemOrgans(
              asset: "assets/images/skeletalSystem/Cartilages.jpg",
              title: "Cartilages",
              desc:
                  "The function of cartilage is to provide cushioning between bones, support soft tissues, and aid in joint movement."),
          ItemOrgans(
              asset: "assets/images/skeletalSystem/skelton/ligaments.png",
              title: "Ligaments",
              desc:
                  "The function of ligaments is to connect bones to other bones and provide stability to joints."),
          ItemOrgans(
              asset: "assets/images/skeletalSystem/skelton/Picture26.png",
              title: "Tendos",
              desc:
                  "The function of tendons is to connect muscles to bones and transmit the force generated by muscle contractions to produce movement."),
          const ItemSystem(
            asset:
                "assets/images/skeletalSystem/Knee_joint-removebg-preview.png",
            title: "Joints",
            desc:
                "The function of joints is to allow for movement and provide mechanical support and flexibility between bones.",
            menu: Joints(),
          ),

         
        const AddVideo(youtubeUrl: "https://youtu.be/-lrKDRAbP38"),
          
          

          SizedBox(
            child: Padding(
              padding: EdgeInsets.symmetric(horizontal: 35.h),
              child: ElevatedButton(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) {
                          return const Quiz_Skelton();
                        },
                      ),
                    );
                  },
                  style: ElevatedButton.styleFrom(
                    fixedSize: Size(100.w, 50.h),
                    backgroundColor: const Color(0xffA8FFBF),
                  ),
                  child: Text(
                    "Take Quiz",
                    style: TextStyle(
                        fontSize: 22.sp,
                        fontWeight: FontWeight.bold,
                        color: Colors.black),
                  )),
            ),
          ),
          SizedBox(
            height: 30.h,
          ),
        ],
      ),
    );
  }

  
}
